# Generated by Django 5.0.7 on 2024-07-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('headshot', models.ImageField(upload_to='headshots/')),
                ('height', models.FloatField()),
            ],
        ),
    ]
